#!/usr/bin/env node
// Replaces bare-ws (Pear/Bare runtime only) with a Node.js-compatible shim
// that wraps the standard 'ws' npm package.  Run automatically via postinstall.

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const target = join(__dirname, '..', 'node_modules', 'bare-ws', 'index.js');

const shim = `// Node.js shim for bare-ws — wraps the standard 'ws' package.
// Auto-generated by scripts/patch-bare-ws.js (postinstall).

const { WebSocketServer, WebSocket } = require('ws')
const EventEmitter = require('events')

class BareSocket extends EventEmitter {
  constructor (ws) {
    super()
    this._ws = ws
    ws.on('message', (data) => this.emit('data', data))
    ws.on('close', () => { this.emit('close'); this.emit('end') })
    ws.on('error', (err) => this.emit('error', err))
  }
  write (data) {
    if (this._ws.readyState === WebSocket.OPEN) this._ws.send(data)
  }
  end () { this._ws.close() }
  destroy () { this._ws.terminate() }
}

class BareServer extends EventEmitter {
  constructor (opts, onconnection) {
    super()
    this._wss = new WebSocketServer({ host: opts.host, port: opts.port }, () => {
      this.emit('listening')
    })
    this._wss.on('connection', (ws) => {
      const socket = new BareSocket(ws)
      if (typeof onconnection === 'function') onconnection(socket)
      this.emit('connection', socket)
    })
    this._wss.on('error', (err) => this.emit('error', err))
  }
  close () { this._wss.close() }
  address () { return this._wss.address() }
}

exports.Server = BareServer
exports.Socket = BareSocket
`;

writeFileSync(target, shim);
console.log('patch-bare-ws: bare-ws shimmed for Node.js');
