#!/usr/bin/env node
// Makes bare-ws work in BOTH Pear/Bare runtime AND Node.js.
// - Pear/Bare: uses the original bare-ws (native addon via require.addon())
// - Node.js: falls back to a shim wrapping the standard 'ws' npm package
//
// Run automatically via postinstall.

import { writeFileSync, readFileSync, copyFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const bareWsDir = join(__dirname, '..', 'node_modules', 'bare-ws');
const target = join(bareWsDir, 'index.js');
const backup = join(bareWsDir, 'index.original.js');

// Step 1: Save the original bare-ws if not already backed up
if (!existsSync(backup)) {
  copyFileSync(target, backup);
  console.log('patch-bare-ws: backed up original bare-ws/index.js → index.original.js');
}

// Step 2: Write a dual-runtime index.js
const shim = `// Dual-runtime bare-ws — works in both Pear/Bare and Node.js.
// Auto-generated by scripts/patch-bare-ws.js (postinstall).

// Detect runtime: Pear/Bare has require.addon, Node.js does not.
if (typeof require !== 'undefined' && typeof require.addon === 'function') {
  // Pear/Bare runtime — load the original bare-ws (native addon)
  const original = require('./index.original.js')
  module.exports = original
} else {
  // Node.js runtime — use ws npm package as shim
  const { WebSocketServer, WebSocket } = require('ws')
  const EventEmitter = require('events')

  class BareSocket extends EventEmitter {
    constructor (ws) {
      super()
      this._ws = ws
      ws.on('message', (data) => this.emit('data', data))
      ws.on('close', () => { this.emit('close'); this.emit('end') })
      ws.on('error', (err) => this.emit('error', err))
    }
    write (data) {
      if (this._ws.readyState === WebSocket.OPEN) this._ws.send(data)
    }
    end () { this._ws.close() }
    destroy () { this._ws.terminate() }
  }

  class BareServer extends EventEmitter {
    constructor (opts, onconnection) {
      super()
      this._wss = new WebSocketServer({ host: opts.host, port: opts.port }, () => {
        this.emit('listening')
      })
      this._wss.on('connection', (ws) => {
        const socket = new BareSocket(ws)
        if (typeof onconnection === 'function') onconnection(socket)
        this.emit('connection', socket)
      })
      this._wss.on('error', (err) => this.emit('error', err))
    }
    close () { this._wss.close() }
    address () { return this._wss.address() }
  }

  module.exports = { Server: BareServer, Socket: BareSocket }
}
`;

writeFileSync(target, shim);
console.log('patch-bare-ws: bare-ws shimmed for dual runtime (Pear + Node.js)');
